# Generated by Django 5.2.5 on 2025-09-09 11:13

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('firewall_service', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('from_email', models.CharField(blank=True, max_length=255, null=True)),
                ('smtp_host', models.CharField(blank=True, max_length=255, null=True)),
                ('smtp_port', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('pending', 'Pending')], default='sent', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Email Log',
                'verbose_name_plural': 'Email Logs',
                'db_table': 'email_log',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='AutomatedEmailSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nom du planning')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('send_time', models.TimeField(default=datetime.time(9, 0), verbose_name="Heure d'envoi")),
                ('timezone', models.CharField(default='UTC', max_length=50, verbose_name='Fuseau horaire')),
                ('include_all_users', models.BooleanField(default=False, verbose_name='Inclure tous les utilisateurs')),
                ('email_subject', models.CharField(max_length=255, verbose_name="Sujet de l'email")),
                ('email_template', models.TextField(verbose_name="Template de l'email")),
                ('commands_to_execute', models.JSONField(default=list, verbose_name='Commandes à exécuter')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('last_sent', models.DateTimeField(blank=True, null=True, verbose_name='Dernier envoi')),
                ('next_send', models.DateTimeField(blank=True, null=True, verbose_name='Prochain envoi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_schedules', to=settings.AUTH_USER_MODEL)),
                ('firewalls', models.ManyToManyField(to='firewall_service.firewall', verbose_name='Pare-feu à vérifier')),
                ('recipients', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Destinataires')),
            ],
            options={
                'verbose_name': 'Planning Email Automatique',
                'verbose_name_plural': 'Plannings Emails Automatiques',
                'db_table': 'automated_email_schedule',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AutomatedEmailExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('execution_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('running', 'En cours'), ('completed', 'Terminé'), ('failed', 'Échoué'), ('cancelled', 'Annulé')], default='pending', max_length=20)),
                ('emails_sent', models.IntegerField(default=0)),
                ('emails_failed', models.IntegerField(default=0)),
                ('commands_executed', models.IntegerField(default=0)),
                ('commands_failed', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('execution_log', models.JSONField(default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='email_service.automatedemailschedule')),
            ],
            options={
                'verbose_name': 'Exécution Email Automatique',
                'verbose_name_plural': 'Exécutions Emails Automatiques',
                'db_table': 'automated_email_execution',
                'ordering': ['-execution_time'],
            },
        ),
        migrations.CreateModel(
            name='CommandExecutionResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('command', models.TextField()),
                ('command_type', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('executing', 'En cours'), ('completed', 'Terminé'), ('failed', 'Échoué'), ('timeout', 'Timeout')], default='pending', max_length=20)),
                ('output', models.TextField(blank=True, null=True)),
                ('error_output', models.TextField(blank=True, null=True)),
                ('exit_code', models.IntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('websocket_session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='command_results', to='email_service.automatedemailexecution')),
                ('firewall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firewall_service.firewall')),
            ],
            options={
                'verbose_name': 'Résultat Exécution Commande',
                'verbose_name_plural': 'Résultats Exécution Commandes',
                'db_table': 'command_execution_result',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='CommandTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('command', models.TextField()),
                ('command_type', models.CharField(default='general', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='command_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Modèle de commande',
                'verbose_name_plural': 'Modèles de commandes',
                'db_table': 'command_template',
                'ordering': ['-created_at'],
                'unique_together': {('owner', 'command', 'command_type')},
            },
        ),
    ]
