# Generated by Django 5.2.5 on 2025-09-09 11:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('firewall_service', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('PENDING', 'Pending')], default='PENDING', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('excel_report', models.TextField(blank=True, null=True)),
                ('historique_dailycheck', models.JSONField(blank=True, default=dict)),
                ('firewall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_checks', to='firewall_service.firewall')),
            ],
            options={
                'ordering': ['-check_date'],
            },
        ),
        migrations.CreateModel(
            name='CheckCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.TextField()),
                ('expected_output', models.TextField(blank=True, null=True)),
                ('actual_output', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('PENDING', 'Pending')], default='PENDING', max_length=50)),
                ('execution_time', models.DateTimeField(auto_now_add=True)),
                ('historique_dailycheck', models.JSONField(blank=True, default=dict)),
                ('daily_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='dailycheck_service.dailycheck')),
            ],
            options={
                'ordering': ['execution_time'],
            },
        ),
    ]
