# Generated by Django 5.2.5 on 2025-09-15 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailycheck_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailycheck',
            name='screenshot_base64',
            field=models.TextField(blank=True, help_text='Base64 encoded screenshot of the firewall dashboard', null=True),
        ),
        migrations.AddField(
            model_name='dailycheck',
            name='screenshot_captured',
            field=models.BooleanField(default=False, help_text='Whether screenshot was successfully captured'),
        ),
    ]
