# Generated by Django 5.2.5 on 2025-09-15 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailycheck_service', '0003_remove_dailycheck_screenshot_base64_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailycheck',
            name='screenshot_base64',
            field=models.TextField(blank=True, help_text='Screenshot du firewall encodé en base64', null=True),
        ),
        migrations.AddField(
            model_name='dailycheck',
            name='screenshot_captured',
            field=models.BooleanField(default=False, help_text='Indique si le screenshot a été capturé avec succès'),
        ),
    ]
