# Generated by Django 4.2.7 on 2025-09-15 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dailycheck_service', '0004_dailycheck_screenshot_base64_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailycheck',
            name='screenshot_base64',
        ),
        migrations.RemoveField(
            model_name='dailycheck',
            name='screenshot_captured',
        ),
    ]
