# Generated by Django 5.2.5 on 2025-09-16 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailycheck_service', '0006_dailycheck_screenshot_base64_and_more'),
        ('firewall_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScriptType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom du type de script', max_length=100, unique=True)),
                ('description', models.TextField(help_text='Description du rôle et du but du script')),
                ('category', models.CharField(choices=[('SECURITY', 'Sécurité'), ('PERFORMANCE', 'Performance'), ('MONITORING', 'Monitoring'), ('MAINTENANCE', 'Maintenance'), ('BACKUP', 'Sauvegarde'), ('CUSTOM', 'Personnalisé')], default='CUSTOM', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Script actif ou non')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Type de Script',
                'verbose_name_plural': 'Types de Scripts',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ScriptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom du template', max_length=100)),
                ('description', models.TextField(help_text='Description du template')),
                ('commands', models.JSONField(help_text='Liste des commandes à exécuter')),
                ('is_default', models.BooleanField(default=False, help_text='Template par défaut pour ce type de script')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('firewall_types', models.ManyToManyField(blank=True, help_text='Types de firewalls compatibles (vide = tous)', to='firewall_service.firewalltype')),
                ('script_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='dailycheck_service.scripttype')),
            ],
            options={
                'verbose_name': 'Template de Script',
                'verbose_name_plural': 'Templates de Scripts',
                'ordering': ['script_type', 'name'],
                'unique_together': {('script_type', 'name')},
            },
        ),
        migrations.AddField(
            model_name='dailycheck',
            name='script_template',
            field=models.ForeignKey(blank=True, help_text='Template de script utilisé', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dailycheck_service.scripttemplate'),
        ),
        migrations.AddField(
            model_name='dailycheck',
            name='script_type',
            field=models.ForeignKey(blank=True, help_text='Type de script utilisé', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dailycheck_service.scripttype'),
        ),
    ]
