# Generated by Django 5.2.5 on 2025-09-16 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailycheck_service', '0007_scripttype_scripttemplate_dailycheck_script_template_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailycheck',
            name='script_template',
        ),
        migrations.AlterField(
            model_name='dailycheck',
            name='script_type',
            field=models.CharField(default='screenshot', help_text='Type de script utilisé pour la capture', max_length=50),
        ),
        migrations.AddField(
            model_name='dailycheck',
            name='script_params',
            field=models.JSONField(blank=True, default=dict, help_text='Paramètres utilisés pour le script'),
        ),
        migrations.AddField(
            model_name='dailycheck',
            name='script_result',
            field=models.JSONField(blank=True, default=dict, help_text='Résultat détaillé du script exécuté'),
        ),
        migrations.DeleteModel(
            name='ScriptTemplate',
        ),
        migrations.DeleteModel(
            name='ScriptType',
        ),
    ]
