# Generated by Django 4.2.7 on 2025-09-16 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dailycheck_service', '0008_remove_dailycheck_script_template_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailycheck',
            name='script_params',
        ),
        migrations.RemoveField(
            model_name='dailycheck',
            name='script_result',
        ),
        migrations.RemoveField(
            model_name='dailycheck',
            name='script_type',
        ),
    ]
