# Generated by Django 5.2.5 on 2025-09-16 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailycheck_service', '0009_remove_dailycheck_script_params_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailycheck',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('PENDING', 'Pending'), ('CONNECTION_FAILED', 'Connection Failed'), ('PARTIAL_SUCCESS', 'Partial Success'), ('ERROR', 'Error'), ('TIMEOUT', 'Timeout')], default='PENDING', max_length=50),
        ),
    ]
