# Generated by Django 4.2.7 on 2025-09-15 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('screenshot_service', '0001_initial'),
    ]

    operations = [
    ]
