# Generated by Django 4.2.7 on 2025-09-15 14:35

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('screenshot_service', '0002_auto_20250915_1321'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreenshotReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(help_text='Adresse IP du firewall')),
                ('protocol', models.CharField(default='https', help_text='Protocole utilisé (http/https)', max_length=10)),
                ('url', models.URLField(help_text='URL complète du firewall')),
                ('screenshot_base64', models.TextField(help_text='Screenshot encodé en base64')),
                ('width', models.IntegerField(default=1366, help_text='Largeur du screenshot')),
                ('height', models.IntegerField(default=768, help_text='Hauteur du screenshot')),
                ('excel_file_path', models.CharField(blank=True, help_text='Chemin vers le fichier Excel généré', max_length=500, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Date de création')),
                ('user', models.CharField(blank=True, help_text='Utilisateur qui a généré le rapport', max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Rapport Screenshot',
                'verbose_name_plural': 'Rapports Screenshots',
                'ordering': ['-created_at'],
            },
        ),
    ]
