# Generated by Django 5.2.5 on 2025-09-09 11:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataCenter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('historique_datacenter', models.JSONField(blank=True, default=dict)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datacenters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'datacenter',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['name'], name='datacenter_name_4f59cf_idx'), models.Index(fields=['owner'], name='datacenter_owner_i_f6198e_idx'), models.Index(fields=['is_active'], name='datacenter_is_acti_778304_idx'), models.Index(fields=['latitude'], name='datacenter_latitud_0668cc_idx'), models.Index(fields=['longitude'], name='datacenter_longitu_a58cff_idx')],
                'unique_together': {('name', 'owner')},
            },
        ),
    ]
