# Generated by Django 5.2.5 on 2025-09-09 11:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('firewall_service', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterfaceAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name="Nom de l'alerte")),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('alert_type', models.CharField(choices=[('interface_down', 'Interface Down'), ('interface_up', 'Interface Up'), ('bandwidth_high', 'Bande passante élevée'), ('error_count', "Compteur d'erreurs"), ('custom', 'Personnalisé')], max_length=50, verbose_name="Type d'alerte")),
                ('check_interval', models.IntegerField(default=300, help_text='Intervalle en secondes (forcé à 5 min)')),
                ('threshold_value', models.FloatField(blank=True, help_text='Valeur seuil pour les alertes numériques', null=True)),
                ('command_template', models.TextField(default='show system interface', help_text='Commande à exécuter')),
                ('conditions', models.JSONField(default=dict, help_text="Conditions personnalisées pour l'alerte")),
                ('include_admin', models.BooleanField(default=True, verbose_name='Inclure les admins')),
                ('include_superuser', models.BooleanField(default=True, verbose_name='Inclure les superusers')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('last_check', models.DateTimeField(blank=True, null=True, verbose_name='Dernière vérification')),
                ('last_status', models.CharField(default='unknown', max_length=20, verbose_name='Dernier statut')),
                ('next_check', models.DateTimeField(blank=True, null=True, verbose_name='Prochaine vérification')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_interface_alerts', to=settings.AUTH_USER_MODEL)),
                ('firewall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firewall_service.firewall', verbose_name='Firewall')),
                ('recipients', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Destinataires')),
            ],
            options={
                'verbose_name': 'Alerte Interface',
                'verbose_name_plural': 'Alertes Interfaces',
                'db_table': 'interface_alert',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('running', 'En cours'), ('completed', 'Terminé'), ('failed', 'Échoué'), ('cancelled', 'Annulé')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration', models.FloatField(blank=True, help_text='Durée en secondes', null=True)),
                ('interfaces_checked', models.IntegerField(default=0)),
                ('alerts_triggered', models.IntegerField(default=0)),
                ('emails_sent', models.IntegerField(default=0)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='interface_monitor_service.interfacealert')),
            ],
            options={
                'verbose_name': "Exécution d'Alerte",
                'verbose_name_plural': "Exécutions d'Alertes",
                'db_table': 'alert_execution',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='InterfaceStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('interface_name', models.CharField(max_length=100, verbose_name="Nom de l'interface")),
                ('status', models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('error', 'Error'), ('unknown', 'Unknown'), ('disabled', 'Disabled')], max_length=20, verbose_name='Statut')),
                ('bandwidth_in', models.FloatField(blank=True, help_text='Bande passante entrante (Mbps)', null=True)),
                ('bandwidth_out', models.FloatField(blank=True, help_text='Bande passante sortante (Mbps)', null=True)),
                ('error_count', models.IntegerField(default=0, help_text="Nombre d'erreurs")),
                ('packet_loss', models.FloatField(blank=True, help_text='Perte de paquets (%)', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('mac_address', models.CharField(blank=True, max_length=17, verbose_name='Adresse MAC')),
                ('raw_output', models.TextField(blank=True, help_text='Sortie brute de la commande')),
                ('last_seen', models.DateTimeField(auto_now_add=True, verbose_name='Dernière observation')),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_checks', to='interface_monitor_service.interfacealert')),
            ],
            options={
                'verbose_name': 'Statut Interface',
                'verbose_name_plural': 'Statuts Interfaces',
                'db_table': 'interface_status',
                'ordering': ['-last_seen'],
            },
        ),
        migrations.AddIndex(
            model_name='interfacealert',
            index=models.Index(fields=['firewall'], name='interface_a_firewal_9161b0_idx'),
        ),
        migrations.AddIndex(
            model_name='interfacealert',
            index=models.Index(fields=['alert_type'], name='interface_a_alert_t_13dd49_idx'),
        ),
        migrations.AddIndex(
            model_name='interfacealert',
            index=models.Index(fields=['is_active'], name='interface_a_is_acti_c30f7c_idx'),
        ),
        migrations.AddIndex(
            model_name='interfacealert',
            index=models.Index(fields=['next_check'], name='interface_a_next_ch_37fe20_idx'),
        ),
        migrations.AddIndex(
            model_name='alertexecution',
            index=models.Index(fields=['alert'], name='alert_execu_alert_i_cd1c41_idx'),
        ),
        migrations.AddIndex(
            model_name='alertexecution',
            index=models.Index(fields=['status'], name='alert_execu_status_e4c7da_idx'),
        ),
        migrations.AddIndex(
            model_name='alertexecution',
            index=models.Index(fields=['started_at'], name='alert_execu_started_5f5efc_idx'),
        ),
        migrations.AddIndex(
            model_name='interfacestatus',
            index=models.Index(fields=['alert'], name='interface_s_alert_i_e4db0d_idx'),
        ),
        migrations.AddIndex(
            model_name='interfacestatus',
            index=models.Index(fields=['interface_name'], name='interface_s_interfa_36dd82_idx'),
        ),
        migrations.AddIndex(
            model_name='interfacestatus',
            index=models.Index(fields=['status'], name='interface_s_status_1e3b7b_idx'),
        ),
        migrations.AddIndex(
            model_name='interfacestatus',
            index=models.Index(fields=['last_seen'], name='interface_s_last_se_4cbd15_idx'),
        ),
        migrations.AddIndex(
            model_name='interfacestatus',
            index=models.Index(fields=['alert', 'status', 'last_seen'], name='idx_alert_status_seen'),
        ),
    ]
