# Generated by Django 5.2.5 on 2025-09-09 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firewall_service', '0001_initial'),
        ('interface_monitor_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interfacealert',
            name='firewall_type',
            field=models.CharField(blank=True, help_text='Type de firewall (ex: FortiGate, Cisco, etc.)', max_length=100),
        ),
        migrations.AddField(
            model_name='interfacealert',
            name='firewalls',
            field=models.ManyToManyField(blank=True, related_name='interface_alerts', to='firewall_service.firewall', verbose_name='Firewalls'),
        ),
        migrations.AlterField(
            model_name='interfacealert',
            name='check_interval',
            field=models.IntegerField(default=360, help_text='Intervalle en secondes (forcé à 6 min)'),
        ),
        migrations.AlterField(
            model_name='interfacealert',
            name='firewall',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='firewall_service.firewall', verbose_name='Firewall (optionnel)'),
        ),
    ]
