# Generated by Django 5.2.5 on 2025-09-09 11:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('firewall_service', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TerminalSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('firewall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terminal_sessions', to='firewall_service.firewall')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terminal_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Terminal Session',
                'verbose_name_plural': 'Terminal Sessions',
                'db_table': 'terminal_session',
            },
        ),
        migrations.CreateModel(
            name='TerminalCommand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('command', models.TextField()),
                ('command_id', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('executing', 'Executing'), ('completed', 'Completed'), ('failed', 'Failed')], default='executing', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='websocket_service.terminalsession')),
            ],
            options={
                'verbose_name': 'Terminal Command',
                'verbose_name_plural': 'Terminal Commands',
                'db_table': 'terminal_command',
                'ordering': ['-created_at'],
            },
        ),
    ]
