# Generated by Django 5.2.5 on 2025-09-09 11:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.CharField(default=str, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('ip_address', models.CharField(max_length=45)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('latitude', models.CharField(blank=True, max_length=20, null=True)),
                ('longitude', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_online', models.BooleanField(default=False)),
                ('last_ping', models.DateTimeField(blank=True, null=True)),
                ('historique_camera', models.JSONField(blank=True, default=dict)),
                ('last_ping_all', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cameras', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'camera',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PingResult',
            fields=[
                ('id', models.CharField(default=str, max_length=36, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=20)),
                ('response_time', models.FloatField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('task_id', models.CharField(blank=True, max_length=50, null=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ping_results', to='camera_service.camera')),
            ],
            options={
                'db_table': 'ping_result',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='camera',
            index=models.Index(fields=['name'], name='camera_name_fbf7c6_idx'),
        ),
        migrations.AddIndex(
            model_name='camera',
            index=models.Index(fields=['ip_address'], name='camera_ip_addr_617065_idx'),
        ),
        migrations.AddIndex(
            model_name='camera',
            index=models.Index(fields=['owner'], name='camera_owner_i_0fc0e6_idx'),
        ),
        migrations.AddIndex(
            model_name='camera',
            index=models.Index(fields=['is_online'], name='camera_is_onli_0dcde4_idx'),
        ),
        migrations.AddIndex(
            model_name='camera',
            index=models.Index(fields=['last_ping'], name='camera_last_pi_033006_idx'),
        ),
        migrations.AddIndex(
            model_name='camera',
            index=models.Index(fields=['last_ping_all'], name='camera_last_pi_ee88b6_idx'),
        ),
        migrations.AddIndex(
            model_name='pingresult',
            index=models.Index(fields=['camera'], name='ping_result_camera__900108_idx'),
        ),
        migrations.AddIndex(
            model_name='pingresult',
            index=models.Index(fields=['status'], name='ping_result_status_c79684_idx'),
        ),
        migrations.AddIndex(
            model_name='pingresult',
            index=models.Index(fields=['timestamp'], name='ping_result_timesta_492aba_idx'),
        ),
        migrations.AddIndex(
            model_name='pingresult',
            index=models.Index(fields=['task_id'], name='ping_result_task_id_663642_idx'),
        ),
    ]
