# Generated by Django 5.2.5 on 2025-09-09 11:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('firewall_service', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FirewallConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('config_data', models.JSONField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('firewall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to='firewall_service.firewall')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firewall_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'firewall_config',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['firewall'], name='firewall_co_firewal_695b37_idx'), models.Index(fields=['owner'], name='firewall_co_owner_i_24031e_idx'), models.Index(fields=['created_at'], name='firewall_co_created_f5b479_idx'), models.Index(fields=['version'], name='firewall_co_version_e5a94c_idx')],
            },
        ),
    ]
