# Generated by Django 5.2.5 on 2025-09-09 11:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datacenter_service', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FirewallType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('attributes_schema', models.JSONField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('historique_firewall', models.JSONField(blank=True, default=dict)),
                ('data_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firewall_types', to='datacenter_service.datacenter')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firewall_types', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'firewall_type',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Firewall',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField()),
                ('ssh_user', models.CharField(default='admin', help_text="Nom d'utilisateur SSH", max_length=50)),
                ('ssh_password', models.CharField(blank=True, help_text='Mot de passe SSH (optionnel)', max_length=255)),
                ('ssh_port', models.IntegerField(default=22, help_text='Port SSH')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('historique_firewall', models.JSONField(blank=True, default=dict)),
                ('data_center', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='firewalls', to='datacenter_service.datacenter')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firewalls', to=settings.AUTH_USER_MODEL)),
                ('firewall_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firewalls', to='firewall_service.firewalltype')),
            ],
            options={
                'db_table': 'firewall',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='firewalltype',
            index=models.Index(fields=['name'], name='firewall_ty_name_ca032b_idx'),
        ),
        migrations.AddIndex(
            model_name='firewalltype',
            index=models.Index(fields=['data_center'], name='firewall_ty_data_ce_ab800c_idx'),
        ),
        migrations.AddIndex(
            model_name='firewalltype',
            index=models.Index(fields=['owner'], name='firewall_ty_owner_i_5c7586_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='firewalltype',
            unique_together={('name', 'data_center')},
        ),
        migrations.AddIndex(
            model_name='firewall',
            index=models.Index(fields=['name'], name='firewall_name_147fa3_idx'),
        ),
        migrations.AddIndex(
            model_name='firewall',
            index=models.Index(fields=['data_center'], name='firewall_data_ce_b0ff44_idx'),
        ),
        migrations.AddIndex(
            model_name='firewall',
            index=models.Index(fields=['firewall_type'], name='firewall_firewal_803d0a_idx'),
        ),
        migrations.AddIndex(
            model_name='firewall',
            index=models.Index(fields=['owner'], name='firewall_owner_i_99f57d_idx'),
        ),
    ]
