# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['run_app.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('firewallbackend', 'firewallbackend'),
        ('static', 'static'),
        ('templates', 'templates'),
        ('db.sqlite3', '.'),
        ('firewall_service', 'firewall_service'),
        ('datacenter_service', 'datacenter_service'),
        ('config_service', 'config_service'),
        ('command_service', 'command_service'),
        ('camera_service', 'camera_service'),
        ('auth_service', 'auth_service'),
        ('analysis_service', 'analysis_service'),
        ('template_service', 'template_service'),
        ('dailycheck_service', 'dailycheck_service'),
        ('dashboard_service', 'dashboard_service'),
        ('history_service', 'history_service'),
    ],
    hiddenimports=[
        'django',
        'django.middleware',
        'django.contrib.admin',
        'django.contrib.auth',
        'django.contrib.contenttypes',
        'django.contrib.sessions',
        'django.contrib.messages',
        'django.contrib.staticfiles',
        'django.contrib.sites',
        'rest_framework',
        'rest_framework.authtoken',
        'rest_framework.authentication',
        'rest_framework.permissions',
        'rest_framework.views',
        'rest_framework.viewsets',
        'rest_framework.routers',
        'rest_framework.serializers',
        'rest_framework.filters',
        'rest_framework.pagination',
        'rest_framework.response',
        'rest_framework.request',
        'rest_framework.status',
        'rest_framework.decorators',
        'rest_framework.mixins',
        'rest_framework.generics',
        'rest_framework.metadata',
        'rest_framework.metadata.base',
        'rest_framework.metadata.simple',
        'rest_framework.schemas',
        'rest_framework.schemas.coreapi',
        'rest_framework.schemas.generators',
        'rest_framework.schemas.utils',
        'rest_framework.schemas.views',
        'rest_framework.settings',
        'rest_framework.utils',
        'rest_framework.utils.field_mapping',
        'rest_framework.utils.model_meta',
        'rest_framework.utils.serializer_helpers',
        'rest_framework_simplejwt',
        'rest_framework_simplejwt.authentication',
        'rest_framework_simplejwt.tokens',
        'rest_framework_simplejwt.views',
        'rest_framework_simplejwt.state',
        'rest_framework_simplejwt.settings',
        'rest_framework_simplejwt.exceptions',
        'rest_framework_simplejwt.backends',
        'rest_framework_simplejwt.token_blacklist',
        'rest_framework_simplejwt.utils',
        'corsheaders',
        'corsheaders.middleware',
        'django_filters',
        'django_filters.rest_framework',
        'whitenoise',
        'whitenoise.middleware',
        'whitenoise.storage',
        'whitenoise.django',
        'firewall_service',
        'datacenter_service',
        'config_service',
        'command_service',
        'camera_service',
        'auth_service',
        'analysis_service',
        'template_service',
        'dailycheck_service',
        'dashboard_service',
        'history_service',
        'django_extensions',
        'pymysql',
        'python_dotenv',
        'gunicorn',
        'ipaddress',
        'paramiko',
        'pythonping',
        'waitress',
        'cryptography',
        'pandas',
        'xlsxwriter',
        'jinja2',
    ],
    hookspath=['.'],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='FirewallApp',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
