# Generated by Django 5.2.5 on 2025-09-09 11:13

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardStats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_firewalls', models.IntegerField(default=0)),
                ('active_firewalls', models.IntegerField(default=0)),
                ('total_datacenters', models.IntegerField(default=0)),
                ('total_users', models.IntegerField(default=0)),
                ('recent_commands', models.IntegerField(default=0)),
                ('pending_tasks', models.IntegerField(default=0)),
                ('system_health', models.CharField(default='warning', max_length=20)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Dashboard Statistics',
                'verbose_name_plural': 'Dashboard Statistics',
                'db_table': 'dashboard_stats',
            },
        ),
    ]
